name: Generate Templates

on:
  push:
    tags:
      - "*"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare each folder
        run: |
          ls
          pwd
          #cp report-template/template.typ singlefile-template/template.typ
          #cp report-template/template.typ report-template-empty/template.typ

      - name: Zip each folder
        run: |
          zip -r singlefile-template.zip singlefile-template
          zip -r report-template.zip report-template
          zip -r report-template-empty.zip report-template-empty

      - name: Upload Singlefile-template
        uses: actions/upload-artifact@v2
        with:
          name: Singlefile template
          path: singlefile-template.zip

      - name: Upload Report-template
        uses: actions/upload-artifact@v2
        with:
          name: Report template
          path: report-template.zip
      
      - name: Upload Singlefile-template
        uses: actions/upload-artifact@v2
        with:
          name: Empty report template
          path: report-template-empty.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            singlefile-template.zip
            report-template.zip
            report-template-empty.zip